version: 1.0.01
fileName: currency
currencies:
    'PAYPAL SUPPORTED':
        'AUD $': 'Australian Dollar (A$)'
        'BRL R$': 'Brazilian Real'
        'GBP £': 'British Pound (£)'
        'CAD $': 'Canadian Dollar (C$)'
        'CZK Kč': 'Czech Koruna'
        'DKK kr': 'Danish Krone'
        'EUR €': 'Euro (€)'
        'HKD $': 'Hong Kong Dollar ($)'
        'HUF Ft': 'Hungarian Forint'
        'ILS ₪': 'Israeli New Shekel'
        'JPY ¥': 'Japanese Yen (¥)'
        'MYR RM': 'Malaysian Ringgit'
        'MXN $': 'Mexican Peso'
        'TWD $': 'New Taiwan Dollar'
        'NZD $': 'New Zealand Dollar ($)'
        'NOK kr': 'Norwegian Krone'
        'PHP ₱': 'Philippine Peso'
        'PLN zl': 'Polish Zloty'
        'SGD $': 'Singapore Dollar ($)'
        'CHF': 'Swiss Franc'
        'THB ฿': 'Thai Baht (฿)'
        'TRY ₺': 'Turkish Lira (₺)'
        'USD $': 'U.S. Dollar ($)' 
    'OTHERS':
        'BDT ó': Bangladeshi Taka (ó)
        'BTC': Bitcoin
        'BGN лв.': Bulgarian Lev (лв.)
        'XAF FCFA': Central African Francs (FCFA)
        'EGP £': Egyptian Pound (£)
        'GHS GH₵': Ghanaian Cedi (GH₵)
        'INR ₹': Indian Rupee (₹)
        'IDR Rp': Indonesian Rupiah (Rp)
        'JMD $': Jamaican Dollar ($)
        'KES KSh': Kenyan Shilling (KSh)
        'MOP MOP$': Macanese Pataca (MOP$)
        'MMK K': Myanmar Kyat (K)
        'NAD N$': Namibian Dollar (N$)
        'NPR ₨': Nepalese Rupee (₨)
        'NGN ₦': Nigerian Naira (₦)
        'PKR ₨': Pakistani Rupee (₨)
        'SAR ﷼‎': Saudi Riyal (﷼‎)
        'TZS TSh': Tanzania Shillings (TSh)
        'VND ₫‎': Vietnamese Dong (₫‎)
