# Relationship List for students and staff
version: 1.1.00
fileName: schoolData
relationships:
    1: 'Parent'
    2: 'Spouse'
    3: 'Offspring'
    4: 'Friend'
    5: 'Other Relation'
    5: 'Family Friend'
    6: 'Doctor'
    7: 'Other'
titles:
    'Ms': 'Ms'
    'Miss': 'Miss'
    'Mr': 'Mr'
    'Mrs': 'Mrs'
    'Dr': 'Dr'
    'Rev.': Rev. 
staff:
    role:
        'Learning Area':
            'Coordinator': 'Coordinator'
            "Assistant Coordinator": 'Assistant Coordinator'
            "Teacher (Curriculum)": 'Teacher (Curriculum)'
            "Teacher": 'Teacher'
            "Other": 'Other'
        "Administration":
            "Director": 'Director'
            "Manager": 'Manager'
            "Administrator": 'Administrator'
            "Other": 'Other'
        Unknown:
            Other: Other 
family:
    relationships:
        1: Mother
        2: Father
        3: Step-Mother
        4: Step-Father
        5: Adoptive Parent
        6: Guardian
        7: GrandMother
        8: GrandFather
        9: Aunt
        10: Uncle
        11: Nanny/Helper
        12: Other
Phone Types:
    1: Mobile
    2: Home
    3: Work
    4: Fascimile
    5: Other
Medical Conditions:
    0004: Allergy - Animal
    0003: Allergy - Drug
    0001: Allergy - Food
    0005: Allergy - Grass/Pollen
    0002: Allergy - Insect
    0006: Allergy - Other
    0007: Asthma
    0012: Convulsions/Epilepsy
    0010: Diabetes
    0018: Dizziness or Fainting spells
    0020: Frequent Nose Bleeds
    0008: G6PD Deficiency
    0022: Hearing Impairment
    0015: Heart Condition
    0011: Hypertension
    0009: Joint Problems
    0013: Kidney Disease
    0027: Other
    0016: Previous Concussion or Head Injury
    0017: Previous Serious Injury
    0021: Psychological Condition
    0014: Rare Blood Type
    0019: Rheumatic Fever
    0026: Travel Sickness
    0023: Visual Impairment
    0025: Visual Impairment - Colour Blindness
    0024: Visual Impairment - Requiring Contact Lenses or Glasses